### ISSUE TITLE
The title "Flower Basket" isn't clickable, Add hover effect on nav bar and fix navigation links

### ISSUE THREAD

**Issue by ReaganBlade** [letscodedanish/OpenSource-Workshop#1]
Apparently the "Flower Basket" title isn't clickable and doesn't redirect to home page which most websites do

Navigation bar doesn't have any hover effect

The links on the footer are unresponsive

**Comment by letscodedanish** [comment]
Okay great @ReaganBlade try to make a descriptive PR from the next time. Also try to add screenshots to describe the particular problem.

**Comment by letscodedanish** [comment]
> Apparently the "Flower Basket" title isn't clickable and doesn't redirect to home page which most websites do
> 
> Navigation bar doesn't have any hover effect
> 
> The links on the footer are unresponsive

Okay make a new PR

**Comment by ReaganBlade** [comment]
> > Apparently the "Flower Basket" title isn't clickable and doesn't redirect to home page which most websites do
> > Navigation bar doesn't have any hover effect
> > The links on the footer are unresponsive
> 
> Okay make a new PR

For the new Issue or the same one?
